name: run-github-workflows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate-environment-files:
    name: validate packages.tsv and generate ${{ matrix.os }}.yml
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-22.04
          tcy_os: linux
        - os: ubuntu-24.04
          tcy_os: linux
        - os: ubuntu-26.04
          tcy_os: linux
        - os: windows-2025
          tcy_os: windows
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v7
      with:
        ref: ${{ github.head_ref }}
    - name: set up Python
      uses: actions/setup-python@v7
      with:
        python-version: 3.11
    - name: install tcy dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pandas
        python -m pip install frictionless
    - name: validate packages.tsv and generate environment file
      run: python -m tcy ${{ matrix.tcy_os }} --yml_name=${{ matrix.os }} --yml_dir=./environments --yml_file_name=${{ matrix.os }}.yml --tsv_path=./environments/packages.tsv
    - name: upload environment file
      uses: actions/upload-artifact@v7
      with:
        name: generated-${{ matrix.os }}
        path: ./environments/${{ matrix.os }}.yml

  solve-environments-and-upload-files:
    name: create environment and export environment files
    needs: generate-environment-files
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04,ubuntu-24.04,ubuntu-26.04,windows-2025]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - name: checkout repository
      uses: actions/checkout@v7
      with:
        ref: ${{ github.head_ref }}
    - name: download environment file
      uses: actions/download-artifact@v8
      with:
        name: generated-${{ matrix.os }}
        path: ./environments
    - name: setup micromamba and create a conda environment using the .yml file that tcy produced
      uses: mamba-org/setup-micromamba@v3
      with:
        environment-file: ./environments/${{ matrix.os }}.yml
        environment-name: ${{ matrix.os }}
    - name: export conda environment both as .yml file and as a spec-file.txt and export the pip-packages as requirements.txt file
      run: |
        micromamba env export -n "${{ matrix.os }}" | grep -vE '^prefix: ' | sed -E "s/^name:.*/name: ${{ matrix.os }}/" > "./environments/${{ matrix.os }}_solved.yml"
        micromamba env export -n "${{ matrix.os }}" --explicit > "./environments/${{ matrix.os }}_solved.txt"
        micromamba run -n "${{ matrix.os }}" pip freeze | grep -v "@ file" > "./environments/${{ matrix.os }}_solved_pip-requirements.txt"
    - name: upload exported files as artifacts
      uses: actions/upload-artifact@v7
      with:
        name: ${{ matrix.os }}
        path: |
          ./environments/${{ matrix.os }}.yml
          ./environments/${{ matrix.os }}_solved.yml
          ./environments/${{ matrix.os }}_solved.txt
          ./environments/${{ matrix.os }}_solved_pip-requirements.txt
  download-artifacts-and-push:
    name: download all files that were created by the runners and push them to repo (but only if something has changed)
    if: ${{ always() }}
    needs: solve-environments-and-upload-files
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v7
      with:
        ref: ${{ github.head_ref }}
    - name: download all files that were created using different operating systems
      uses: actions/download-artifact@v8
      with:
        pattern: '{ubuntu-*,windows-*}'
        path: ./environments
    - name: add and commit files (but only if something has changed)
      uses: stefanzweifel/git-auto-commit-action@v7
